package com.teamup.service;

import com.teamup.dto.GroupReportResponse;
import com.teamup.model.Role;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.ss.util.CellRangeAddress;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

@Service
@RequiredArgsConstructor
@Slf4j
public class ReportService {

    private final DashboardService dashboardService;

    private static final DateTimeFormatter DTF = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
    private static final DateTimeFormatter FILE_DTF = DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss");

    // ──────────────────────────────────────────────
    // Public entry points
    // ──────────────────────────────────────────────

    public byte[] generateExcelReport(Long groupId, Long teacherId) {
        GroupReportResponse report = dashboardService.buildGroupReport(groupId, teacherId);
        return buildExcel(report);
    }

    public byte[] generatePdfReport(Long groupId, Long teacherId) {
        GroupReportResponse report = dashboardService.buildGroupReport(groupId, teacherId);
        return buildPdf(report);
    }

    // ──────────────────────────────────────────────
    // Excel Generation — Apache POI
    // ──────────────────────────────────────────────

    private byte[] buildExcel(GroupReportResponse report) {
        try (Workbook workbook = new XSSFWorkbook();
             ByteArrayOutputStream out = new ByteArrayOutputStream()) {

            // ── Sheet 1: Group Summary ──────────────────────
            Sheet summarySheet = workbook.createSheet("Group Summary");
            buildSummarySheet(summarySheet, report, workbook);

            // ── Sheet 2: Contribution Breakdown ─────────────
            Sheet contribSheet = workbook.createSheet("Contribution %");
            buildContributionSheet(contribSheet, report, workbook);

            // ── Sheet 3: Submission History ─────────────────
            Sheet subSheet = workbook.createSheet("Submission History");
            buildSubmissionSheet(subSheet, report, workbook);

            // ── Sheet 4: Peer Review Scores ────────────────
            Sheet prSheet = workbook.createSheet("Peer Review Scores");
            buildPeerReviewSheet(prSheet, report, workbook);

            workbook.write(out);
            log.info("Excel report generated for group {}", report.getGroupId());
            return out.toByteArray();

        } catch (IOException e) {
            log.error("Failed to generate Excel report", e);
            throw new RuntimeException("Failed to generate Excel report", e);
        }
    }

    private void buildSummarySheet(Sheet sheet, GroupReportResponse report, Workbook wb) {
        CellStyle headerStyle = headerStyle(wb);
        CellStyle boldStyle = boldStyle(wb);
        CellStyle normalStyle = normalStyle(wb);

        int row = 0;

        Row title = sheet.createRow(row++);
        Cell titleCell = title.createCell(0);
        titleCell.setCellValue("TEAMUP — GROUP REPORT");
        titleCell.setCellStyle(boldStyle(wb));
        titleCell.getCellStyle().setFont(boldFont(wb));

        addRow(sheet, row++, new String[]{"Group Name", report.getGroupName()}, normalStyle(wb));
        addRow(sheet, row++, new String[]{"Class ID", report.getClassId()}, normalStyle(wb));
        addRow(sheet, row++, new String[]{"Generated At", report.getGeneratedAt()}, normalStyle(wb));
        addRow(sheet, row++, new String[]{"Generated By", report.getGeneratedBy() != null ? report.getGeneratedBy() : "Teacher"}, normalStyle(wb));

        row++; // blank row

        // Member headers
        Row memberHeader = sheet.createRow(row++);
        String[] headers = {"#", "Name", "Email", "Role", "Contribution %", "Tasks", "Completed", "Avg Progress", "Peer Score", "Peer Reviews"};
        for (int i = 0; i < headers.length; i++) {
            Cell cell = memberHeader.createCell(i);
            cell.setCellValue(headers[i]);
            cell.setCellStyle(headerStyle);
        }

        int idx = 1;
        for (GroupReportResponse.MemberReport member : report.getMembers()) {
            Row r = sheet.createRow(row++);
            r.createCell(0).setCellValue(idx++);
            r.createCell(1).setCellValue(member.getName());
            r.createCell(2).setCellValue(member.getEmail());
            r.createCell(3).setCellValue(member.getRole());
            r.createCell(4).setCellValue(member.getContributionPercent() != null ? member.getContributionPercent() : 0.0);
            r.createCell(5).setCellValue(member.getTaskCount());
            r.createCell(6).setCellValue(member.getCompletedTaskCount() != null ? member.getCompletedTaskCount() : 0);
            r.createCell(7).setCellValue(member.getAverageProgress() != null ? member.getAverageProgress() : 0.0);
            r.createCell(8).setCellValue(member.getPeerReviewScore() != null ? member.getPeerReviewScore() : 0.0);
            r.createCell(9).setCellValue(member.getPeerReviewCount() != null ? member.getPeerReviewCount() : 0);
            for (int i = 0; i < 10; i++) r.getCell(i).setCellStyle(normalStyle(wb));
        }

        // Auto-size columns
        for (int i = 0; i < 10; i++) sheet.autoSizeColumn(i);
    }

    private void buildContributionSheet(Sheet sheet, GroupReportResponse report, Workbook wb) {
        CellStyle headerStyle = headerStyle(wb);
        CellStyle normalStyle = normalStyle(wb);
        CellStyle pctStyle = percentStyle(wb);

        Row header = sheet.createRow(0);
        String[] headers = {"Name", "Contribution %", "Tasks Assigned", "Avg Progress", "Status"};
        for (int i = 0; i < headers.length; i++) {
            Cell cell = header.createCell(i);
            cell.setCellValue(headers[i]);
            cell.setCellStyle(headerStyle);
        }

        int row = 1;
        for (GroupReportResponse.MemberReport member : report.getMembers()) {
            Row r = sheet.createRow(row++);
            r.createCell(0).setCellValue(member.getName());
            Cell pctCell = r.createCell(1);
            pctCell.setCellValue((member.getContributionPercent() != null ? member.getContributionPercent() : 0.0) / 100.0);
            pctCell.setCellStyle(pctStyle);
            r.createCell(2).setCellValue(member.getTaskCount());
            r.createCell(3).setCellValue(member.getAverageProgress() != null ? member.getAverageProgress() : 0.0);
            r.createCell(4).setCellValue(
                    member.getContributionPercent() != null && member.getContributionPercent() >= 33.0 ? "Active"
                    : member.getContributionPercent() != null && member.getContributionPercent() > 0 ? "Low Contribution"
                    : "No Contribution"
            );
            for (int i = 0; i < 5; i++) r.getCell(i).setCellStyle(normalStyle(wb));
        }

        for (int i = 0; i < 5; i++) sheet.autoSizeColumn(i);
    }

    private void buildSubmissionSheet(Sheet sheet, GroupReportResponse report, Workbook wb) {
        CellStyle headerStyle = headerStyle(wb);
        CellStyle normalStyle = normalStyle(wb);
        CellStyle goodStyle = greenStyle(wb);
        CellStyle badStyle = redStyle(wb);

        Row header = sheet.createRow(0);
        String[] headers = {"Member", "Task Name", "File URL", "Submitted At", "Deadline", "On Time?"};
        for (int i = 0; i < headers.length; i++) {
            Cell cell = header.createCell(i);
            cell.setCellValue(headers[i]);
            cell.setCellStyle(headerStyle);
        }

        int row = 1;
        for (GroupReportResponse.MemberReport member : report.getMembers()) {
            for (GroupReportResponse.SubmissionHistory sub : member.getSubmissions()) {
                Row r = sheet.createRow(row++);
                r.createCell(0).setCellValue(member.getName());
                r.createCell(1).setCellValue(sub.getTaskName());
                r.createCell(2).setCellValue(sub.getFileUrl());
                r.createCell(3).setCellValue(sub.getSubmittedAt());
                r.createCell(4).setCellValue(sub.getDeadline() != null ? sub.getDeadline() : "No deadline");
                Cell onTimeCell = r.createCell(5);
                onTimeCell.setCellValue(sub.isOnTime() ? "YES" : "LATE");
                onTimeCell.setCellStyle(sub.isOnTime() ? goodStyle : badStyle);
                for (int i = 0; i < 5; i++) r.getCell(i).setCellStyle(normalStyle(wb));
            }
        }

        for (int i = 0; i < 6; i++) sheet.autoSizeColumn(i);
    }

    private void buildPeerReviewSheet(Sheet sheet, GroupReportResponse report, Workbook wb) {
        CellStyle headerStyle = headerStyle(wb);
        CellStyle normalStyle = normalStyle(wb);

        Row header = sheet.createRow(0);
        String[] headers = {"Name", "Peer Review Score (avg /5)", "Reviews Received", "Role"};
        for (int i = 0; i < headers.length; i++) {
            Cell cell = header.createCell(i);
            cell.setCellValue(headers[i]);
            cell.setCellStyle(headerStyle);
        }

        int row = 1;
        for (GroupReportResponse.MemberReport member : report.getMembers()) {
            Row r = sheet.createRow(row++);
            r.createCell(0).setCellValue(member.getName());
            Cell scoreCell = r.createCell(1);
            if (member.getPeerReviewScore() != null) {
                scoreCell.setCellValue(member.getPeerReviewScore());
            } else {
                scoreCell.setCellValue("N/A");
            }
            r.createCell(2).setCellValue(member.getPeerReviewCount() != null ? member.getPeerReviewCount() : 0);
            r.createCell(3).setCellValue(member.getRole());
            for (int i = 0; i < 4; i++) r.getCell(i).setCellStyle(normalStyle(wb));
        }

        for (int i = 0; i < 4; i++) sheet.autoSizeColumn(i);
    }

    // ──────────────────────────────────────────────
    // PDF Generation — iText 7
    // ──────────────────────────────────────────────

    private byte[] buildPdf(GroupReportResponse report) {
        try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            var writer = new com.itextpdf.kernel.pdf.PdfWriter(out);
            var pdfDoc = new com.itextpdf.kernel.pdf.PdfDocument(writer);
            var document = new com.itextpdf.layout.Document(pdfDoc);

            // Title
            var title = new com.itextpdf.layout.element.Paragraph("TEAMUP — GROUP REPORT")
                    .setFontSize(18)
                    .setBold()
                    .setTextAlignment(com.itextpdf.layout.properties.TextAlignment.CENTER);
            document.add(title);

            // Group info
            addPdfInfo(document, "Group Name", report.getGroupName());
            addPdfInfo(document, "Class ID", report.getClassId());
            addPdfInfo(document, "Generated At", report.getGeneratedAt());
            addPdfInfo(document, "Generated By", report.getGeneratedBy() != null ? report.getGeneratedBy() : "Teacher");
            document.add(new com.itextpdf.layout.element.Paragraph("\n"));

            // Member contribution table
            var memberHeader = new String[]{"Name", "Contribution %", "Tasks", "Completed", "Avg Progress", "Peer Score"};
            var memberTable = buildPdfTable(memberHeader, report.getMembers().size());
            var memberTableImpl = (com.itextpdf.layout.element.Table) memberTable;

            int idx = 0;
            for (GroupReportResponse.MemberReport member : report.getMembers()) {
                int rowIdx = idx + 1;
                com.itextpdf.layout.element.Cell nameCell = new com.itextpdf.layout.element.Cell().add(new com.itextpdf.layout.element.Paragraph(safe(member.getName())));
                com.itextpdf.layout.element.Cell contribCell = new com.itextpdf.layout.element.Cell().add(new com.itextpdf.layout.element.Paragraph(fmt(member.getContributionPercent())));
                com.itextpdf.layout.element.Cell tasksCell = new com.itextpdf.layout.element.Cell().add(new com.itextpdf.layout.element.Paragraph(String.valueOf(member.getTaskCount())));
                com.itextpdf.layout.element.Cell completedCell = new com.itextpdf.layout.element.Cell().add(new com.itextpdf.layout.element.Paragraph(String.valueOf(member.getCompletedTaskCount() != null ? member.getCompletedTaskCount() : 0)));
                com.itextpdf.layout.element.Cell avgCell = new com.itextpdf.layout.element.Cell().add(new com.itextpdf.layout.element.Paragraph(fmt(member.getAverageProgress())));
                com.itextpdf.layout.element.Cell scoreCell = new com.itextpdf.layout.element.Cell().add(new com.itextpdf.layout.element.Paragraph(member.getPeerReviewScore() != null ? fmt(member.getPeerReviewScore()) + " /5" : "N/A"));
                memberTable.addCell(rowIdx, 0, nameCell);
                memberTable.addCell(rowIdx, 1, contribCell);
                memberTable.addCell(rowIdx, 2, tasksCell);
                memberTable.addCell(rowIdx, 3, completedCell);
                memberTable.addCell(rowIdx, 4, avgCell);
                memberTable.addCell(rowIdx, 5, scoreCell);
                idx++;
            }

            document.add(new com.itextpdf.layout.element.Paragraph("Member Contribution Breakdown")
                    .setFontSize(14).setBold());
            document.add(memberTableImpl);
            document.add(new com.itextpdf.layout.element.Paragraph("\n"));

            // Submission history
            document.add(new com.itextpdf.layout.element.Paragraph("Submission History")
                    .setFontSize(14).setBold());

            boolean hasSubmissions = report.getMembers().stream()
                    .anyMatch(m -> m.getSubmissions() != null && !m.getSubmissions().isEmpty());

            if (hasSubmissions) {
                var subHeaders = new String[]{"Member", "Task", "Submitted At", "Deadline", "On Time?"};
                int totalRows = report.getMembers().stream()
                        .mapToInt(m -> m.getSubmissions() != null ? m.getSubmissions().size() : 0)
                        .sum();
                if (totalRows > 0) {
                    var subTable = buildPdfTable(subHeaders, totalRows);
                    var subTableImpl = (com.itextpdf.layout.element.Table) subTable;
                    int subIdx = 0;
                    for (GroupReportResponse.MemberReport member : report.getMembers()) {
                        for (GroupReportResponse.SubmissionHistory sub : member.getSubmissions()) {
                            int rowIdx = subIdx + 1;
                            com.itextpdf.layout.element.Cell mCell = new com.itextpdf.layout.element.Cell().add(new com.itextpdf.layout.element.Paragraph(safe(member.getName())));
                            com.itextpdf.layout.element.Cell tCell = new com.itextpdf.layout.element.Cell().add(new com.itextpdf.layout.element.Paragraph(safe(sub.getTaskName())));
                            com.itextpdf.layout.element.Cell sCell = new com.itextpdf.layout.element.Cell().add(new com.itextpdf.layout.element.Paragraph(safe(sub.getSubmittedAt())));
                            com.itextpdf.layout.element.Cell dCell = new com.itextpdf.layout.element.Cell().add(new com.itextpdf.layout.element.Paragraph(safe(sub.getDeadline())));
                            com.itextpdf.layout.element.Cell oCell = new com.itextpdf.layout.element.Cell().add(new com.itextpdf.layout.element.Paragraph(sub.isOnTime() ? "YES" : "LATE"));
                            subTable.addCell(rowIdx, 0, mCell);
                            subTable.addCell(rowIdx, 1, tCell);
                            subTable.addCell(rowIdx, 2, sCell);
                            subTable.addCell(rowIdx, 3, dCell);
                            subTable.addCell(rowIdx, 4, oCell);
                            subIdx++;
                        }
                    }
                    document.add(subTableImpl);
                } else {
                    document.add(new com.itextpdf.layout.element.Paragraph("No submissions recorded yet."));
                }
            } else {
                document.add(new com.itextpdf.layout.element.Paragraph("No submissions recorded yet."));
            }

            // Footer
            document.add(new com.itextpdf.layout.element.Paragraph("\n\n")
                    .setFontSize(8)
                    .setTextAlignment(com.itextpdf.layout.properties.TextAlignment.RIGHT)
                    .add("Generated by TeamUp on " + LocalDateTime.now().format(DTF)));

            document.close();
            log.info("PDF report generated for group {}", report.getGroupId());
            return out.toByteArray();

        } catch (IOException e) {
            log.error("Failed to generate PDF report", e);
            throw new RuntimeException("Failed to generate PDF report", e);
        }
    }

    private void addPdfInfo(com.itextpdf.layout.Document document, String label, String value) {
        var row = new com.itextpdf.layout.element.Paragraph(label + ": ")
                .setFontSize(10).add(value != null ? value : "N/A");
        document.add(row);
    }

    private com.itextpdf.layout.element.Table buildPdfTable(String[] headers, int rows) {
        var table = new com.itextpdf.layout.element.Table(headers.length).useAllAvailableWidth();

        // Header row
        for (String h : headers) {
            table.addHeaderCell(new com.itextpdf.layout.element.Cell()
                    .add(new com.itextpdf.layout.element.Paragraph(h).setBold())
                    .setBackgroundColor(new com.itextpdf.kernel.colors.DeviceRgb(44, 62, 80))
                    .setFontColor(com.itextpdf.kernel.colors.ColorConstants.WHITE));
        }

        // Data rows
        for (int i = 0; i < rows; i++) {
            for (String ignored : headers) {
                table.addCell(new com.itextpdf.layout.element.Cell());
            }
        }

        return table;
    }

    // ──────────────────────────────────────────────
    // Cell style helpers — Apache POI
    // ──────────────────────────────────────────────

    private CellStyle headerStyle(Workbook wb) {
        CellStyle style = wb.createCellStyle();
        org.apache.poi.ss.usermodel.Font font = wb.createFont();
        font.setBold(true);
        font.setColor(IndexedColors.WHITE.getIndex());
        style.setFont(font);
        style.setFillForegroundColor(new org.apache.poi.xddf.usermodel.colors.XDDFColor(new java.awt.Color(44, 62, 80)));
        style.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        style.setBorderBottom(BorderStyle.THIN);
        style.setBorderTop(BorderStyle.THIN);
        style.setBorderLeft(BorderStyle.THIN);
        style.setBorderRight(BorderStyle.THIN);
        return style;
    }

    private CellStyle normalStyle(Workbook wb) {
        CellStyle style = wb.createCellStyle();
        style.setBorderBottom(BorderStyle.THIN);
        style.setBorderTop(BorderStyle.THIN);
        style.setBorderLeft(BorderStyle.THIN);
        style.setBorderRight(BorderStyle.THIN);
        return style;
    }

    private CellStyle boldStyle(Workbook wb) {
        CellStyle style = wb.createCellStyle();
        org.apache.poi.ss.usermodel.Font font = wb.createFont();
        font.setBold(true);
        style.setFont(font);
        return style;
    }

    private org.apache.poi.ss.usermodel.Font boldFont(Workbook wb) {
        org.apache.poi.ss.usermodel.Font font = wb.createFont();
        font.setBold(true);
        font.setFontHeightInPoints((short) 14);
        return font;
    }

    private CellStyle percentStyle(Workbook wb) {
        CellStyle style = wb.createCellStyle();
        DataFormat format = wb.createDataFormat();
        style.setDataFormat(format.getFormat("0.00%"));
        style.setBorderBottom(BorderStyle.THIN);
        style.setBorderTop(BorderStyle.THIN);
        style.setBorderLeft(BorderStyle.THIN);
        style.setBorderRight(BorderStyle.THIN);
        return style;
    }

    private CellStyle greenStyle(Workbook wb) {
        CellStyle style = wb.createCellStyle();
        style.setFillForegroundColor(IndexedColors.LIGHT_GREEN.getIndex());
        style.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        style.setBorderBottom(BorderStyle.THIN);
        style.setBorderTop(BorderStyle.THIN);
        style.setBorderLeft(BorderStyle.THIN);
        style.setBorderRight(BorderStyle.THIN);
        return style;
    }

    private CellStyle redStyle(Workbook wb) {
        CellStyle style = wb.createCellStyle();
        style.setFillForegroundColor(IndexedColors.CORAL.getIndex());
        style.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        style.setBorderBottom(BorderStyle.THIN);
        style.setBorderTop(BorderStyle.THIN);
        style.setBorderLeft(BorderStyle.THIN);
        style.setBorderRight(BorderStyle.THIN);
        return style;
    }

    // ──────────────────────────────────────────────
    // Utility helpers
    // ──────────────────────────────────────────────

    private void addRow(Sheet sheet, int rowNum, String[] values, CellStyle style) {
        Row r = sheet.createRow(rowNum);
        for (int i = 0; i < values.length; i++) {
            Cell cell = r.createCell(i);
            cell.setCellValue(values[i]);
            cell.setCellStyle(style);
        }
    }

    private String fmt(Double val) {
        return val != null ? String.format("%.2f", val) : "0.00";
    }

    private String safe(String val) {
        return val != null ? val : "N/A";
    }
}
